//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class beveragesWithFunctionWithMenu
    {
        public int beveragesWithDesertWithFunctionWithMenuID { get; set; }
        public int beverageID { get; set; }
        public int quantityBeverages { get; set; }
        public int dishID { get; set; }
        public int requestID { get; set; }
        public int PriceBeverages { get; set; }
    
        public virtual Beverage Beverage { get; set; }
        public virtual Dish Dish { get; set; }
        public virtual FunctionRequestedTable FunctionRequestedTable { get; set; }
    }
}
