//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookingdata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookingdata()
        {
            this.AdditionalFacilitiesandFunctions = new HashSet<AdditionalFacilitiesandFunction>();
        }
    
        public int functionID { get; set; }
        public System.DateTime bookingDate { get; set; }
        public System.DateTime functionDate { get; set; }
        public int noofGuest { get; set; }
        public int rateperGuest { get; set; }
        public Nullable<int> stagesCharges { get; set; }
        public int basics_others { get; set; }
        public int Extras { get; set; }
        public int TotalCharges { get; set; }
        public string timeShift { get; set; }
        public int MenuId { get; set; }
        public int ProgramId { get; set; }
        public string CnicNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalFacilitiesandFunction> AdditionalFacilitiesandFunctions { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Program Program { get; set; }
    }
}
