//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CnicNo { get; set; }
        public string customerName { get; set; }
        public string mobileNo { get; set; }
        public string address { get; set; }
        public string remarks { get; set; }
    }
}
