//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desert()
        {
            this.DesertWithFunctionWithMenus = new HashSet<DesertWithFunctionWithMenu>();
            this.QuantityupdatedDeserttables = new HashSet<QuantityupdatedDeserttable>();
        }
    
        public int desertId { get; set; }
        public string desertName { get; set; }
        public int desertSalePrice { get; set; }
        public int desertPurchasePrice { get; set; }
        public int quantityOfdesert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesertWithFunctionWithMenu> DesertWithFunctionWithMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuantityupdatedDeserttable> QuantityupdatedDeserttables { get; set; }
    }
}
