//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishWithItem
    {
        public int dishAndItemID { get; set; }
        public int requestID { get; set; }
        public int dishId { get; set; }
        public int itemId { get; set; }
        public int qunatityOfItems { get; set; }
        public int priceOfItems { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Item Item { get; set; }
        public virtual FunctionRequestedTable FunctionRequestedTable { get; set; }
    }
}
