//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionRequestedTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FunctionRequestedTable()
        {
            this.beveragesWithFunctionWithMenus = new HashSet<beveragesWithFunctionWithMenu>();
            this.DesertWithFunctionWithMenus = new HashSet<DesertWithFunctionWithMenu>();
            this.DishWithItems = new HashSet<DishWithItem>();
        }
    
        public int requestID { get; set; }
        public int functionID { get; set; }
        public System.DateTime requestDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beveragesWithFunctionWithMenu> beveragesWithFunctionWithMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesertWithFunctionWithMenu> DesertWithFunctionWithMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DishWithItem> DishWithItems { get; set; }
        public virtual Bookingdata Bookingdata { get; set; }
    }
}
