//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramsandMenu
    {
        public int menuandProgramID { get; set; }
        public Nullable<int> menuID { get; set; }
        public Nullable<int> programID { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Program Program { get; set; }
    }
}
