//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAccountBalance
    {
        public int accountbalanceID { get; set; }
        public int subID { get; set; }
        public System.DateTime Date { get; set; }
        public long Debit { get; set; }
        public long Credit { get; set; }
        public int accountNo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual subTypesOfHeadAccount subTypesOfHeadAccount { get; set; }
    }
}
